server:
  port: 8081
spring:
  cloud: 
   gateway:
    globalcors:
      cors-configurations:
        '[/**]':
          allowedOrigins: '*'
          allowedHeaders: '*'
          allowedMethods: 
          - GET
          - POST
          - PUT
          - DELETE
    routes:
      - id: event
        uri: lb://event/
        predicates:
          - Path=/event/**
      - id: user
        uri: lb://user/
        predicates:
          - Path=/user/**
      - id: buy
        uri: lb://buy/
        predicates:
          - Path=/buy/**
