server:
  port: 8081
spring:
  cloud: 
   gateway:
    globalcors:
     corsConfigurations:
      '[/**]':
        allowedOrigins: '*'
        allowedHeaders: '*'
         allowedMethods: GET, POST, DELETE, PUT
    routes:
      - id: event
        uri: lb://event/
        predicates:
          - Path=/event/**
      - id: user
        uri: lb://user/
        predicates:
          - Path=/user/**
      - id: buy
        uri: lb://buy/
        predicates:
          - Path=/buy/**
       
